### ISSUE TITLE
Compilation error messages no longer display in document view

### ISSUE THREAD

**Issue by michael-hawker** [dotnet/XAMLStudio#13]
Seems like if there's an issue it's only highlighted in the editor, but there's no display that there's a problem (outside of maybe new tab indicator)

Should maybe have an error infobar pop up?

**Comment by michael-hawker** [comment]
Fixed in `titlebar-rework` branch, was disabled when updating to 8.x toolkit due to `DropShadowPanel` shift, didn't convert over to new pattern. InfoBar works better now anyway for most things I think, though eventually hope can move to better parsing paradigm: https://github.com/michael-hawker/XmlSyntaxVisualizerUWP/issues/4
